name: tech_savvy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk:
      flutter
      # Cupertino icons for iOS design
  cupertino_icons: ^1.0.6
  flutter_localizations:
    # Provides localization support
    sdk: flutter

    # A Flutter plugin for adapting screen and font size

  flutter_screenutil:
    ^5.9.1
    # Linter rules used by the Very Good Ventures
  very_good_analysis: ^5.1.0
  # Bloc for state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

dev_dependencies:
  # Lints for Flutter projects
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
    # Path to onboarding images
    - assets/images/onboarding/
    - lang/ar.json
    - lang/en.json


  fonts:
    # Arabic fonts
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400

    # English fonts
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
