name: tech_savvy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.11
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.1
  font_awesome_flutter: ^10.7.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    # Path to onboarding images
    - assets/images/onboarding/
      # Path to home images
    - assets/images/home/
      # Path to searchbar images
    - assets/images/searchbaricons/
      # Path to course category images
    - assets/images/coursecategory/
      # Path to languages
    - lang/ar.json
    - lang/en.json

  fonts:
    # Arabic fonts
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400

    # English fonts
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
